import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { money } from "../utils/formatters";

export const generatePDF = async (appState, lang = 'es') => {
  const { user = {}, expenses = [], income = [], shared = [], debts = [], goals = [], budgets = {} } = appState;
  
  const totalInc = income.reduce((a, i) => a + i.amount, 0);
  const totalExp = expenses.reduce((a, e) => a + e.amount, 0);
  const balance = totalInc - totalExp;
  const cur = user.currency || "RD$";
  
  // Agrupar gastos por categoría
  const cats = {};
  expenses.forEach(e => { cats[e.cat] = (cats[e.cat] || 0) + e.amount; });
  const sortedCats = Object.entries(cats).sort((a,b) => b[1] - a[1]);

  const totalSharedOwed = shared.reduce((a,p) => a + p.balance, 0);
  const totalDebt = debts.reduce((a, d) => a + d.balance, 0);

  const T = {
    titulo: lang === 'en' ? "EXECUTIVE FINANCIAL REPORT" : "REPORTE FINANCIERO EJECUTIVO",
    usuario: lang === 'en' ? "Fynx User" : "Usuario Fynx",
    fecha: lang === 'en' ? "DATE" : "FECHA",
    ingresos: lang === 'en' ? "Gross Inflow" : "Flujo de Entrada (Ingresos)",
    gastos: lang === 'en' ? "Gross Outflow" : "Salida de Capital (Egresos)",
    balance: lang === 'en' ? "Net Liquidity" : "Liquidez Neta",
    analisis: lang === 'en' ? "Expense Distribution & Sector Analysis" : "Distribución de Egresos y Análisis Sectorial",
    cat: lang === 'en' ? "Category" : "Clasificación de Egresos",
    prop: lang === 'en' ? "Proportion" : "Proporción",
    monto: lang === 'en' ? "Amount" : "Monto",
    sinRegistros: lang === 'en' ? "No records available" : "No hay registros disponibles",
    
    // Deudas
    deudasTitulo: lang === 'en' ? "Capital Structure (Liabilities)" : "Estructura de Capital (Pasivos)",
    deudaNom: lang === 'en' ? "Liability / Creditor" : "Pasivo / Acreedor",
    tasa: lang === 'en' ? "APR" : "Tasa Anual",
    deudaBal: lang === 'en' ? "Outstanding Balance" : "Saldo Insoluto",
    
    // Metas
    metasTitulo: lang === 'en' ? "Capital Objectives Projection" : "Proyección de Objetivos de Capital",
    metaNom: lang === 'en' ? "Objective" : "Objetivo",
    metaProg: lang === 'en' ? "Progress" : "Progreso",
    metaBal: lang === 'en' ? "Target / Saved" : "Meta / Ahorrado",

    // Presupuestos
    presupTitulo: lang === 'en' ? "Budget Performance Analysis" : "Análisis de Rendimiento de Presupuesto",
    presupCat: lang === 'en' ? "Sector" : "Sector",
    presupStatus: lang === 'en' ? "Execution Level" : "Nivel de Ejecución",
    presupLimit: lang === 'en' ? "Limit / Spent" : "Límite / Ejecutado",

    compartidos: lang === 'en' ? "Accounts Receivable" : "Cuentas por Cobrar",
    deudor: lang === 'en' ? "Debtor" : "Deudor",
    balPend: lang === 'en' ? "Pending Balance" : "Balance Pendiente",
    totalCobrar: lang === 'en' ? "TOTAL RECEIVABLE" : "TOTAL POR COBRAR",
    
    recientes: lang === 'en' ? "Recent Transaction Ledger" : "Libro Mayor de Transacciones Recientes",
    fechaOp: lang === 'en' ? "Op. Date" : "Fecha Op.",
    concepto: lang === 'en' ? "Concept" : "Concepto",
    impacto: lang === 'en' ? "Financial Impact" : "Impacto Financiero",
    
    confidencial: lang === 'en' ? "CONFIDENTIAL. DOCUMENT GENERATED BY FYNX WEALTH MANAGEMENT SYSTEM." : "CONFIDENCIAL. DOCUMENTO GENERADO POR FYNX WEALTH MANAGEMENT SYSTEM.",
    disclaimer: lang === 'en' ? "DISCLAIMER: This document is an automated financial summary based on user input. It does not constitute certified legal or accounting advice." : "AVISO LEGAL: Este documento es un resumen financiero automatizado basado en datos ingresados por el usuario. No constituye asesoría contable ni legal certificada.",
    footerMoneda: lang === 'en' ? `ALL VALUES IN LOCAL CURRENCY (${cur}).` : `TODOS LOS VALORES EN MONEDA LOCAL (${cur}).`,
    compartir: lang === 'en' ? "Share Financial Report" : "Compartir Reporte Financiero",
  };

  const html = `
    <!DOCTYPE html>
    <html lang="${lang}">
    <head>
      <meta charset="UTF-8">
      <title>Fynx Wealth Management - ${T.titulo}</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800;900&display=swap');
        * { box-sizing: border-box; }
        body { font-family: 'Inter', sans-serif; background-color: #080808; color: #FFFFFF; padding: 50px; margin: 0; background-image: radial-gradient(circle at 50% 0%, #1a1500 0%, #080808 60%); }
        
        .header { display: flex; justify-content: space-between; align-items: flex-end; padding-bottom: 25px; border-bottom: 1px solid rgba(212, 175, 55, 0.4); margin-bottom: 40px; }
        .logo-container { display: flex; flex-direction: column; }
        .logo { font-size: 38px; font-weight: 900; color: #D4AF37; letter-spacing: -1px; margin: 0; line-height: 1; text-shadow: 0 0 20px rgba(212, 175, 55, 0.4); }
        .logo-sub { font-size: 10px; color: #D4AF37; letter-spacing: 4px; text-transform: uppercase; margin-top: 4px; opacity: 0.8; }
        
        .user-info { text-align: right; }
        .title { font-size: 16px; font-weight: 800; color: #E0E0E0; margin-bottom: 4px; text-transform: uppercase; letter-spacing: 1px; }
        .subtitle { font-size: 11px; color: #888888; font-family: monospace; letter-spacing: 0.5px; }
        
        .summary-cards { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 40px; }
        .card { background: #111; border: 1px solid rgba(212, 175, 55, 0.2); border-radius: 12px; padding: 25px; position: relative; }
        .card::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 2px; background: linear-gradient(90deg, transparent, #D4AF37, transparent); opacity: 0.5; }
        .card-title { font-size: 10px; color: #888; text-transform: uppercase; letter-spacing: 1.5px; margin-bottom: 8px; font-weight: 800; }
        .card-value { font-size: 24px; font-weight: 800; color: #FFFFFF; font-family: monospace; }
        .card-value.income { color: #00FF9D; }
        .card-value.expense { color: #FF4A4A; }
        .card-value.balance { color: #D4AF37; }

        .section-title { font-size: 13px; font-weight: 800; color: #D4AF37; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 15px; display: flex; align-items: center; margin-top: 35px; }
        .section-title::after { content: ''; flex: 1; height: 1px; background: rgba(212, 175, 55, 0.2); margin-left: 15px; }
        
        .table-container { background: #0a0a0a; border: 1px solid rgba(255, 255, 255, 0.08); border-radius: 12px; overflow: hidden; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 14px 20px; text-align: left; }
        th { background-color: rgba(212, 175, 55, 0.05); color: #D4AF37; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; font-weight: 800; border-bottom: 1px solid rgba(212, 175, 55, 0.2); }
        td { font-size: 12px; color: #E0E0E0; border-bottom: 1px solid rgba(255, 255, 255, 0.05); }
        tr:last-child td { border-bottom: none; }
        
        .text-right { text-align: right; }
        .mono { font-family: monospace; }
        
        /* BARS */
        .bar-bg { width: 100px; height: 4px; background: #222; border-radius: 2px; overflow: hidden; display: inline-block; vertical-align: middle; margin-left: 10px; }
        .bar-fill { height: 100%; background: #D4AF37; border-radius: 2px; }
        .bar-fill.danger { background: #FF4A4A; }
        .bar-fill.safe { background: #00FF9D; }
        .bar-fill.warn { background: #FFC107; }

        .footer { text-align: center; margin-top: 60px; padding-top: 20px; border-top: 1px dashed rgba(255, 255, 255, 0.1); }
        .footer p { font-size: 9px; color: #666666; margin: 4px 0; letter-spacing: 0.5px; font-family: monospace; }
        .footer-logo { font-size: 14px; font-weight: 900; color: #D4AF37; letter-spacing: 2px; opacity: 0.5; margin-bottom: 10px; }
        .disclaimer { font-size: 8px !important; margin-top: 15px !important; color: #444 !important; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo-container">
          <h1 class="logo">FYNX</h1>
          <div class="logo-sub">WEALTH MANAGEMENT</div>
        </div>
        <div class="user-info">
          <div class="title">${T.titulo}</div>
          <div class="subtitle">CLIENT: ${user.name || user.email || T.usuario} | ${T.fecha}: ${new Date().toLocaleDateString(lang === 'en' ? 'en-US' : 'es-DO')}</div>
        </div>
      </div>

      <div class="summary-cards">
        <div class="card">
          <div class="card-title">${T.ingresos}</div>
          <div class="card-value income">${money(totalInc, cur)}</div>
        </div>
        <div class="card">
          <div class="card-title">${T.gastos}</div>
          <div class="card-value expense">${money(totalExp, cur)}</div>
        </div>
        <div class="card">
          <div class="card-title">${T.balance}</div>
          <div class="card-value balance">${money(balance, cur)}</div>
        </div>
      </div>

      <!-- PRESUPUESTOS (Nivel de Ejecución) -->
      ${Object.keys(budgets).length > 0 ? `
      <div class="section-title">${T.presupTitulo}</div>
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>${T.presupCat}</th>
              <th class="text-right">${T.presupStatus}</th>
              <th class="text-right">${T.presupLimit}</th>
            </tr>
          </thead>
          <tbody>
            ${Object.entries(budgets).map(([cat, limit]) => {
              const spent = expenses.filter(e => e.cat === cat).reduce((a,e) => a + e.amount, 0);
              const pct = Math.min(100, Math.round((spent / limit) * 100));
              const colorClass = pct > 90 ? 'danger' : pct > 75 ? 'warn' : 'safe';
              const catName = require("../constants").CATS[cat]?.label?.[lang] || cat;
              return '<tr><td>' + catName + '</td>' +
                '<td class="text-right"><span class="mono" style="color:#888; font-size:10px;">' + pct + '%</span>' +
                '<div class="bar-bg"><div class="bar-fill ' + colorClass + '" style="width: ' + pct + '%;"></div></div></td>' +
                '<td class="text-right mono">' + money(spent, cur) + ' / ' + money(limit, cur) + '</td></tr>';
            }).join('')}
          </tbody>
        </table>
      </div>
      ` : ''}

      <!-- DISTRIBUCIÓN DE EGRESOS -->
      <div class="section-title">${T.analisis}</div>
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>${T.cat}</th>
              <th class="text-right">${T.prop}</th>
              <th class="text-right">${T.monto}</th>
            </tr>
          </thead>
          <tbody>
            ${sortedCats.length > 0 ? sortedCats.map(([cat, amount]) => {
              const pct = totalExp > 0 ? Math.round((amount/totalExp)*100) : 0;
              const catName = require("../constants").CATS[cat]?.label?.[lang] || cat;
              return '<tr><td>' + catName + '</td>' +
                '<td class="text-right"><span class="mono" style="color:#888; font-size:10px;">' + pct + '%</span>' +
                '<div class="bar-bg"><div class="bar-fill" style="width: ' + pct + '%;"></div></div></td>' +
                '<td class="text-right mono">' + money(amount, cur) + '</td></tr>';
            }).join('') : `<tr><td colspan="3" style="text-align:center; color: #666; padding: 20px;">${T.sinRegistros}</td></tr>`}
          </tbody>
        </table>
      </div>

      <!-- DEUDAS (Estructura de Pasivos) -->
      ${debts.length > 0 ? `
      <div class="section-title">${T.deudasTitulo}</div>
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>${T.deudaNom}</th>
              <th class="text-right">CYCLES</th>
              <th class="text-right">${T.tasa}</th>
              <th class="text-right">${T.deudaBal}</th>
            </tr>
          </thead>
          <tbody>
            ${debts.sort((a,b) => b.balance - a.balance).map(d => 
              '<tr><td>' + d.name + '</td>' +
              '<td class="text-right mono" style="color:#888; font-size:9px;">' + (d.statementDay || d.dueDay ? `S:${d.statementDay||'-'} D:${d.dueDay||'-'}` : '-') + '</td>' +
              '<td class="text-right mono" style="color:#FF4A4A;">' + d.rate + '%</td>' +
              '<td class="text-right mono" style="color:#FF4A4A; font-weight:600;">' + money(d.balance, cur) + '</td></tr>'
            ).join('')}
            <tr>
              <td colspan="2" class="text-right" style="color:#888; font-weight:800; font-size:10px;">TOTAL LIABILITIES</td>
              <td class="text-right mono" style="color:#FF4A4A; font-weight:800;">${money(totalDebt, cur)}</td>
            </tr>
          </tbody>
        </table>
      </div>
      ` : ''}

      <!-- METAS (Objetivos de Capital) -->
      ${goals.length > 0 ? `
      <div class="section-title">${T.metasTitulo}</div>
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>${T.metaNom}</th>
              <th class="text-right">${T.metaProg}</th>
              <th class="text-right">${T.metaBal}</th>
            </tr>
          </thead>
          <tbody>
            ${goals.sort((a,b) => (b.saved/b.target) - (a.saved/a.target)).map(g => {
              const pct = Math.min(100, Math.round((g.saved/g.target)*100));
              return '<tr><td>' + g.name + '</td>' +
                '<td class="text-right"><span class="mono" style="color:#888; font-size:10px;">' + pct + '%</span>' +
                '<div class="bar-bg"><div class="bar-fill safe" style="width: ' + pct + '%;"></div></div></td>' +
                '<td class="text-right mono" style="color:#00FF9D;">' + money(g.saved, cur) + ' / ' + money(g.target, cur) + '</td></tr>';
            }).join('')}
          </tbody>
        </table>
      </div>
      ` : ''}

      <!-- CUENTAS POR COBRAR -->
      ${totalSharedOwed > 0 ? `
      <div class="section-title">${T.compartidos}</div>
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>${T.deudor}</th>
              <th class="text-right">${T.balPend}</th>
            </tr>
          </thead>
          <tbody>
            ${shared.filter(p => p.balance > 0).map(p => 
              '<tr><td><span style="color:#00FF9D; font-size:8px;">●</span> ' + p.name + '</td>' +
              '<td class="text-right mono" style="color: #00FF9D;">' + money(p.balance, cur) + '</td></tr>'
            ).join('')}
            <tr>
              <td style="font-weight:800; color:#888; font-size:10px;">${T.totalCobrar}</td>
              <td class="text-right mono" style="font-weight:800; color:#00FF9D;">${money(totalSharedOwed, cur)}</td>
            </tr>
          </tbody>
        </table>
      </div>
      ` : ''}

      <!-- TRANSACCIONES RECIENTES -->
      <div class="section-title">${T.recientes}</div>
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>${T.fechaOp}</th>
              <th>${T.concepto}</th>
              <th class="text-right">${T.impacto}</th>
            </tr>
          </thead>
          <tbody>
            ${expenses.slice(0, 10).map(e => 
              '<tr><td class="mono" style="color:#888;">' + new Date(e.id).toLocaleDateString(lang === 'en' ? 'en-US' : 'es-DO', {day: '2-digit', month: '2-digit', year: 'numeric'}) + '</td>' +
              '<td>' + (e.desc || (require("../constants").CATS[e.cat]?.label?.[lang] || e.cat)) + '</td>' +
              '<td class="text-right mono" style="color: #FF4A4A;">-' + money(e.amount, cur) + '</td></tr>'
            ).join('')}
          </tbody>
        </table>
      </div>

      <div class="footer">
        <div class="footer-logo">FYNX</div>
        <p>${T.confidencial}</p>
        <p>${T.footerMoneda}</p>
        <p class="disclaimer">${T.disclaimer}</p>
      </div>
    </body>
    </html>
  `;

  try {
    const { uri } = await Print.printToFileAsync({ html, base64: false });
    await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf', dialogTitle: T.compartir });
  } catch (error) {
    console.warn("Error generando PDF:", error);
  }
};
