export const CURRENCIES = [
  { iso: "DOP", symbol: "RD$", name: "Peso Dominicano" },
  { iso: "USD", symbol: "$", name: "US Dollar" },
  { iso: "EUR", symbol: "€", name: "Euro" },
  { iso: "MXN", symbol: "$", name: "Peso Mexicano" },
  { iso: "COP", symbol: "$", name: "Peso Colombiano" },
  { iso: "ARS", symbol: "$", name: "Peso Argentino" },
  { iso: "CLP", symbol: "$", name: "Peso Chileno" },
  { iso: "PEN", symbol: "S/", name: "Sol Peruano" },
  { iso: "BRL", symbol: "R$", name: "Real Brasileño" },
  { iso: "GTQ", symbol: "Q", name: "Quetzal Guatemalteco" },
  { iso: "HNL", symbol: "L", name: "Lempira Hondureño" },
  { iso: "CRC", symbol: "₡", name: "Colón Costarricense" },
  { iso: "PAB", symbol: "B/.", name: "Balboa Panameño" },
  { iso: "BOB", symbol: "Bs.", name: "Boliviano" },
  { iso: "PYG", symbol: "₲", name: "Guaraní Paraguayo" },
  { iso: "UYU", symbol: "$U", name: "Peso Uruguayo" },
  { iso: "HTG", symbol: "G", name: "Gourde Haitiano" },
  { iso: "JMD", symbol: "J$", name: "Dólar Jamaiquino" },
  { iso: "TTD", symbol: "TT$", name: "Dólar Trinitense" },
  { iso: "BBD", symbol: "Bds$", name: "Dólar de Barbados" },
  { iso: "XCD", symbol: "EC$", name: "Dólar del Caribe Oriental" },
  { iso: "CUP", symbol: "₱", name: "Peso Cubano" },
  { iso: "NIO", symbol: "C$", name: "Córdoba Nicaragüense" },
  { iso: "CAD", symbol: "CA$", name: "Canadian Dollar" },
  { iso: "GBP", symbol: "£", name: "British Pound" },
  { iso: "CHF", symbol: "CHF", name: "Swiss Franc" },
  { iso: "SEK", symbol: "kr", name: "Swedish Krona" },
  { iso: "NOK", symbol: "kr", name: "Norwegian Krone" },
  { iso: "DKK", symbol: "kr", name: "Danish Krone" },
  { iso: "ISK", symbol: "kr", name: "Icelandic Króna" },
  { iso: "PLN", symbol: "zł", name: "Polish Zloty" },
  { iso: "CZK", symbol: "Kč", name: "Czech Koruna" },
  { iso: "HUF", symbol: "Ft", name: "Hungarian Forint" },
  { iso: "RON", symbol: "lei", name: "Romanian Leu" },
  { iso: "BGN", symbol: "лв", name: "Bulgarian Lev" },
  { iso: "HRK", symbol: "kn", name: "Croatian Kuna" },
  { iso: "RSD", symbol: "din", name: "Serbian Dinar" },
  { iso: "UAH", symbol: "₴", name: "Ukrainian Hryvnia" },
  { iso: "GEL", symbol: "₾", name: "Georgian Lari" },
  { iso: "JPY", symbol: "¥", name: "Japanese Yen" },
  { iso: "CNY", symbol: "¥", name: "Chinese Yuan" },
  { iso: "KRW", symbol: "₩", name: "South Korean Won" },
  { iso: "HKD", symbol: "HK$", name: "Hong Kong Dollar" },
  { iso: "TWD", symbol: "NT$", name: "New Taiwan Dollar" },
  { iso: "MOP", symbol: "MOP$", name: "Macanese Pataca" },
  { iso: "INR", symbol: "₹", name: "Indian Rupee" },
  { iso: "PKR", symbol: "Rs", name: "Pakistani Rupee" },
  { iso: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
  { iso: "LKR", symbol: "Rs", name: "Sri Lankan Rupee" },
  { iso: "NPR", symbol: "Rs", name: "Nepalese Rupee" },
  { iso: "SGD", symbol: "S$", name: "Singapore Dollar" },
  { iso: "THB", symbol: "฿", name: "Thai Baht" },
  { iso: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { iso: "PHP", symbol: "₱", name: "Philippine Peso" },
  { iso: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { iso: "VND", symbol: "₫", name: "Vietnamese Dong" },
  { iso: "KHR", symbol: "៛", name: "Cambodian Riel" },
  { iso: "MMK", symbol: "K", name: "Myanmar Kyat" },
  { iso: "RUB", symbol: "₽", name: "Russian Ruble" },
  { iso: "KZT", symbol: "₸", name: "Kazakhstani Tenge" },
  { iso: "UZS", symbol: "so'm", name: "Uzbekistani Som" },
  { iso: "AZN", symbol: "₼", name: "Azerbaijani Manat" },
  { iso: "AMD", symbol: "֏", name: "Armenian Dram" },
  { iso: "AED", symbol: "د.إ", name: "UAE Dirham" },
  { iso: "SAR", symbol: "﷼", name: "Saudi Riyal" },
  { iso: "QAR", symbol: "﷼", name: "Qatari Riyal" },
  { iso: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar" },
  { iso: "BHD", symbol: ".د.ب", name: "Bahraini Dinar" },
  { iso: "OMR", symbol: "ر.ع.", name: "Omani Rial" },
  { iso: "JOD", symbol: "د.ا", name: "Jordanian Dinar" },
  { iso: "ILS", symbol: "₪", name: "Israeli New Shekel" },
  { iso: "TRY", symbol: "₺", name: "Turkish Lira" },
  { iso: "IRR", symbol: "﷼", name: "Iranian Rial" },
  { iso: "ZAR", symbol: "R", name: "South African Rand" },
  { iso: "NGN", symbol: "₦", name: "Nigerian Naira" },
  { iso: "KES", symbol: "KSh", name: "Kenyan Shilling" },
  { iso: "GHS", symbol: "GH₵", name: "Ghanaian Cedi" },
  { iso: "EGP", symbol: "E£", name: "Egyptian Pound" },
  { iso: "MAD", symbol: "د.م.", name: "Moroccan Dirham" },
  { iso: "TND", symbol: "د.ت", name: "Tunisian Dinar" },
  { iso: "ETB", symbol: "Br", name: "Ethiopian Birr" },
  { iso: "TZS", symbol: "TSh", name: "Tanzanian Shilling" },
  { iso: "UGX", symbol: "USh", name: "Ugandan Shilling" },
  { iso: "XOF", symbol: "CFA", name: "West African CFA franc" },
  { iso: "XAF", symbol: "FCFA", name: "Central African CFA franc" },
  { iso: "AUD", symbol: "A$", name: "Australian Dollar" },
  { iso: "NZD", symbol: "NZ$", name: "New Zealand Dollar" },
  { iso: "FJD", symbol: "FJ$", name: "Fijian Dollar" },
  { iso: "PGK", symbol: "K", name: "Papua New Guinean Kina" },
  { iso: "BTC", symbol: "₿", name: "Bitcoin" },
  { iso: "ETH", symbol: "Ξ", name: "Ethereum" },
  { iso: "USDT", symbol: "₮", name: "Tether" },
  { iso: "USDC", symbol: "USDC", name: "USD Coin" }
];
