/**
 * FYNX — Archivo maestro de strings
 * PRD v4.0: Centralización total. Prohibido hardcodear texto en componentes.
 * Auditoría RAE: Categoría, Transacción, Gráfica, Perfil — tildes correctas.
 */

export const S = {
  // ── App ───────────────────────────────────────────────────────────────────
  appNombre:  "Fynx",
  semver:     "1.0.0",
  build:      "1",
  package:    "com.fynx.app",
  version:    "v1.0.0",
  cargando:   "Cargando...",
  guardar:    "Guardar",
  cancelar:   "Cancelar",
  eliminar:   "Eliminar",
  aceptar:    "Aceptar",
  cerrar:     "Cerrar",
  atras:      "Atrás",
  siguiente:  "Siguiente",
  finalizar:  "Finalizar",
  sinDatos:   "Sin datos registrados.",
  moneda:     "RD$",
  loading: {
    verificando: "Verificando cuenta...",
    cargando:    "Cargando tus datos...",
    sesion:      "Recuperando sesión...",
    perfil:      "Cargando tu perfil...",
  },

  factors: {
    solidSavings: "Ahorro Sólido",
    spendingExceeds: "Gasto supera Ingresos",
    noIncome: "Sin Ingresos",
    budgetUnderControl: "Presupuesto Controlado",
    categoriesExceeded: (over) => `${over} Categorías Excedidas`,
    noBudgets: "Sin Presupuestos",
    activeStreak: (streak) => `Racha Activa (${streak}d)`,
    reducedSpending: "Gastos Reducidos",
    lowConsistency: "Baja Consistencia",
  },

  // ── Auth ──────────────────────────────────────────────────────────────────
  auth: {
    titulo:       "Bienvenido a Fynx",
    subtitulo:    "Tu asistente financiero personal.",
    lblEmail:     "CORREO ELECTRÓNICO",
    lblPassword:  "CONTRASEÑA",
    phEmail:      "correo@ejemplo.com",
    phPassword:   "Mínimo 6 caracteres",
    btnEntrar:    "Iniciar sesión",
    btnRegistrar: "Crear cuenta",
    linkOlvide:   "¿Olvidaste tu contraseña?",
    linkCrear:    "¿No tienes cuenta? Crear una",
    linkTengo:    "¿Ya tienes cuenta? Inicia sesión",
    enviado:      "Correo de recuperación enviado. Revisa tu bandeja.",
    errCampos:    "Completa todos los campos.",
    errInvalido:  "Correo o contraseña incorrectos.",
    errExiste:    "Este correo ya tiene una cuenta registrada.",
    errDebil:     "La contraseña debe tener mínimo 6 caracteres.",
    errRed:       "Sin conexión. Verifica tu internet.",
    errGeneral:   "Ocurrió un error. Intenta de nuevo.",
    continuarDev: "Continuar sin cuenta (desarrollo)",
    modoDev:      "MODO DESARROLLO",
    verificando:  "Verificando...",
    recuperar:    "Recuperar contraseña",
    recuperarSub: "Te enviaremos un enlace de recuperación.",
    enviarCorreo: "Enviar correo",
  },

  // ── Drawer ────────────────────────────────────────────────────────────────
  drawer: {
    dev: "Pantalla en desarrollo",
    logoutConfirm: "¿Seguro que deseas salir de tu cuenta Fynx Elite?",
    salir: "Salir",
    eliteUser: "Usuario Elite",
    cuenta: "CUENTA",
    miPerfil: "Mi Perfil",
    perfilSub: "Datos personales y plan",
    seguridad: "Seguridad",
    seguridadSub: "Biometría y contraseña",
    finanzas: "FINANZAS",
    estrategia: "Estrategia",
    estrategiaSub: "IA financiera personalizada",
    chatFynx: "Chat Fynx",
    chatSub: "Consulta con tu asistente",
    soporte: "SOPORTE",
    admin: "Panel Elite Admin",
    adminSub: "Estadísticas y uso",
    notificaciones: "Notificaciones",
    notifSub: "Alertas y recordatorios",
    soporteTecnico: "Soporte Técnico",
    soporteSub: "Centro de ayuda Fynx",
    sugerencia: "Enviar Sugerencia",
    sugerenciaSub: "Ayúdanos a mejorar",
    legal: "Legal & Privacidad",
    legalSub: "Términos y condiciones",
    configuracion: "Configuración",
    configSub: "Preferencias de la app",
    logoutPhase: "FASE 2 · Auth Queue"
  },

  // ── Onboarding ────────────────────────────────────────────────────────────
  ob: {
    bienvenida: {
      titulo:   "Fynx",
      subtitulo: "Tu asesor financiero personal.\nInteligente. Privado. Dominicano.",
      cta:      "Comenzar",
    },
    perfil: {
      titulo:   "Tu perfil",
      subtitulo: "¿Cómo te llamas?",
      lblNombre: "NOMBRE",
      lblMoneda: "MONEDA",
      lblMeta:   "META DE AHORRO (%)",
      phNombre:  "Ej.: Erickson",
    },
    ingresos: {
      titulo:    "Tus ingresos",
      subtitulo: "Agrega tus fuentes de ingreso mensual.",
      phFuente:  "Fuente (ej.: Salario, Freelance)",
      phMonto:   "Monto",
      btnAgregar:"Agregar ingreso",
      fijo:      "Fijo",
      variable:  "Variable",
    },
    presupuesto: {
      titulo:    "Presupuesto",
      subtitulo: "Límites mensuales por categoría.",
      phLimite:  "0 = sin límite",
    },
    metas: {
      titulo:    "Primera meta",
      subtitulo: "¿Qué quieres lograr? (opcional)",
      lblQue:    "¿QUÉ QUIERES LOGRAR?",
      lblSimbolo:"SÍMBOLO",
      lblCosto:  "COSTO",
      lblPlazo:  "PLAZO",
      phMeta:    "Ej.: Laptop, Viaje, Fondo de emergencia...",
      phMonto:   "Ej.: 50 000",
      btnAgregar:"Agregar meta",
      plazos: [
        ["4",  "1 mes"],
        ["12", "3 meses"],
        ["24", "6 meses"],
        ["52", "1 año"],
      ],
    },
    fin: {
      titulo:    (nombre) => `Listo, ${nombre || "bienvenido"}.`,
      subtitulo: "Tu ecosistema financiero está configurado.",
      cta:       "Empezar",
    },
    nav: {
      atras:     "Atrás",
      siguiente: "Siguiente",
      finalizar: "Finalizar",
    },
    typewriter: {
      0: "Bienvenido a Fynx.\nAquí tus datos son privados, locales y tuyos.",
      1: "Cuéntame sobre ti.\nEsto personaliza tu experiencia.",
      2: "¿De dónde viene tu dinero?\nRegistrar ingresos es el primer paso.",
      3: "Poner límites es disciplina, no restricción.",
      4: "Una meta transforma el ahorro en motivación.",
      5: "Todo está listo.\nDisciplina financiera de élite, comenzando ahora.",
    },
  },

  // ── Dashboard ─────────────────────────────────────────────────────────────
  dash: {
    titulo:       "Inicio",
    balanceNeto:  "BALANCE NETO",
    ingresos:     "Ingresos",
    gastos:       "Gastos",
    tasaAhorro:   "Tasa de ahorro",
    cobertura:    "Cobertura",
    scoreLabel:   "Score Fynx",
    tendencia:    "Tendencia mensual",
    sinTx:        "Sin transacciones este mes.",
    verTodo:      (n) => `Ver todo (${n})`,
    semVerde:     "Finanzas saludables",
    semAmarillo:  "Precaución recomendada",
    semRojo:      "Atención inmediata",
    diasCobertura:(d) => `${d} días`,
    rachaLabel:   "Racha",
    nivel:        "Nivel",
  },

  // ── Transacciones ─────────────────────────────────────────────────────────
  tx: {
    titulo:       "Transacciones",
    nueva:        "Nueva transacción",
    lblFecha:     "FECHA",
    lblMonto:     "MONTO (RD$)",
    lblCategoria: "CATEGORÍA",
    lblDesc:      "DESCRIPCIÓN",
    lblTipo:      "TIPO",
    tipoGasto:    "Gasto",
    tipoIngreso:  "Ingreso",
    phMonto:      "0.00",
    phDesc:       "Descripción opcional",
    confirmElim:  "¿Eliminar esta transacción?",
    sinRegistros: "Sin registros aún.",
    hoy:          "Hoy",
    ayer:         "Ayer",
  },

  // ── Metas de ahorro ───────────────────────────────────────────────────────
  metas: {
    titulo:       "Metas",
    nueva:        "Nueva meta",
    lblNombre:    "NOMBRE DE LA META",
    lblObjetivo:  "MONTO OBJETIVO (RD$)",
    lblAportado:  "MONTO APORTADO (RD$)",
    phNombre:     "Ej.: Fondo de emergencia",
    phObjetivo:   "Ej.: 100 000",
    progreso:     (p) => `${p}% completado`,
    sinMetas:     "No hay metas definidas.",
    btnAbonar:    "Abonar",
    completada:   "Meta completada",
    faltante:     (m) => `Faltan RD$ ${m}`,
  },

  // ── Categorías ────────────────────────────────────────────────────────────
  cats: {
    titulo:         "Categorías",
    Comida:         "Comida",
    Transporte:     "Transporte",
    Entretenimiento:"Entretenimiento",
    Salud:          "Salud",
    Educacion:      "Educación",
    Ropa:           "Ropa",
    Servicios:      "Servicios",
    Ocio:           "Ocio",
    Ahorro:         "Ahorro",
    Otros:          "Otros",
    Alimentacion:   "Alimentación",
    Transporte:     "Transporte",
    Ocio:           "Ocio",
    Salud:          "Salud",
    Suscripciones:  "Suscripciones",
    Hogar:          "Hogar",
    Educacion:      "Educación",
    Otro:           "Otro",
  },

  deudas: {
    tarjeta:  "Tarjeta de crédito",
    prestamo: "Préstamo",
    hipoteca: "Hipoteca",
    auto:     "Auto",
    personal: "Personal",
    otro:     "Otro",
  },

  frecuencias: {
    diario:    "Diario",
    semanal:   "Semanal",
    quincenal: "Quincenal",
    mensual:   "Mensual",
    diarioSuffix: "/día",
    semanalSuffix: "/semana",
    quincenalSuffix: "/quincena",
    mensualSuffix: "/mes",
  },

  // ── Score ─────────────────────────────────────────────────────────────────
  score: {
    titulo:        "Score Fynx",
    ahorro:        "Tasa de ahorro",
    presupuesto:   "Control de gastos",
    consistencia:  "Consistencia de registro",
    deuda:         "Gestión de deudas",
    disciplina:    "Bono de disciplina",
    reduccion:     "Bono por reducción de gastos",
    excelente:     "Excelente",
    bueno:         "Bueno",
    regular:       "Regular",
    critico:       "Crítico",
  },

  // ── Premium ───────────────────────────────────────────────────────────────
  premium: {
    badge:         "PLAN PREMIUM",
    badgeGratis:   "PLAN GRATUITO",
    btnUpgrade:    "Actualizar a Premium",
    titulo:        "Fynx Elite",
    subtitulo:     "Herramientas avanzadas para finanzas de élite.",
    precio:        "RD$ 299 / mes",
    desde:         "Desde $2.99/mes",
    widgetSub:     "DESBLOQUEA TENDENCIAS Y REPORTES",
    cta:           "Suscribirse ahora",
    noAhora:       "No por ahora",
    beneficios: [
      { icono: "hardware-chip-outline",   titulo: "TARS AI Unlimited",      desc: "Consultas sin límites con tu asesor financiero IA." },
      { icono: "document-text-outline",    titulo: "Reportes PDF",           desc: "Exportación profesional de tu salud financiera." },
      { icono: "stats-chart-outline",      titulo: "Predictor Avanzado",     desc: "Proyecciones de flujo de caja a 6 meses con IA." },
      { icono: "pie-chart-outline",        titulo: "Equidad Proporcional",   desc: "Divide gastos compartidos basado en ingresos." },
      { icono: "globe-outline",            titulo: "Social Score",           desc: "Compara tu disciplina financiera con la comunidad." },
      { icono: "cloud-done-outline",       titulo: "Sincronización Nube",    desc: "Respaldo seguro y acceso en múltiples dispositivos." },
      { icono: "ban-outline",              titulo: "Sin Publicidad",         desc: "Experiencia 100% limpia en toda la plataforma." },
      { icono: "notifications-outline",    titulo: "Notificaciones Elite",   desc: "Resúmenes matutinos y nocturnos inteligentes." },
      { icono: "lock-closed-outline",      titulo: "Bloqueo de 48h",         desc: "Seguridad avanzada para evitar gastos impulsivos." },
      { icono: "star-outline",             titulo: "Soporte Prioritario",    desc: "Atención técnica preferencial en menos de 24h." },
    ],
  },

  // ── Configuración ─────────────────────────────────────────────────────────
  config: {
    titulo:       "Configuración",
    apariencia:   "APARIENCIA",
    temaOscuro:   "Oscuro",
    temaClaro:    "Claro",
    lblNombre:    "NOMBRE",
    lblIngreso:   "INGRESO MENSUAL (RD$)",
    lblMeta:      "META DE AHORRO (%)",
    lblPresup:    "LÍMITES DE PRESUPUESTO (RD$)",
    btnGuardar:   "Guardar cambios",
    cerrarSesion: "Cerrar sesión",
  },

  // ── Freno de emergencia ───────────────────────────────────────────────────
  freno: {
    titulo:   "Freno de emergencia",
    desc:     "Deshabilita Ocio por 48 h cuando gastes de más.",
    activo:   (h) => `Activo — ${h} h restantes.`,
  },

  // ── Legal ─────────────────────────────────────────────────────────────────
  legal: {
    terminos: [
      { titulo: "1. Aceptación de los términos", cuerpo: "Al descargar, instalar o utilizar la aplicación Fynx, usted acepta quedar vinculado por estos Términos y Condiciones. Si no está de acuerdo con alguna parte de los términos, no podrá acceder al servicio." },
      { titulo: "2. Descripción del servicio", cuerpo: "Fynx es una aplicación de gestión financiera personal que permite registrar ingresos, gastos, metas de ahorro y analizar hábitos financieros mediante un sistema de puntuación adaptativo. La aplicación opera tanto en modo local como con sincronización en la nube a través de Firebase." },
      { titulo: "3. Cuenta de usuario", cuerpo: "Para acceder a las funciones de sincronización en la nube, debe crear una cuenta con un correo electrónico válido y una contraseña. Usted es responsable de mantener la confidencialidad de sus credenciales y de todas las actividades que ocurran bajo su cuenta." },
      { titulo: "4. Uso aceptable", cuerpo: "Usted se compromete a utilizar Fynx únicamente para fines personales y legítimos de gestión financiera. Queda prohibido el uso de la aplicación para actividades fraudulentas, ilegales o que perjudiquen a terceros." },
      { titulo: "5. Datos financieros", cuerpo: "Los datos financieros que ingrese en Fynx son de su exclusiva propiedad. Fynx no comparte, vende ni utiliza sus datos financieros con fines comerciales. La información se almacena localmente y, si opta por la sincronización, en servidores seguros de Firebase (Google)." },
      { titulo: "6. Plan Elite", cuerpo: "Fynx ofrece una suscripción Premium con funcionalidades adicionales, incluyendo eliminación de publicidad, exportación de reportes PDF y herramientas avanzadas de predicción. La suscripción se renueva automáticamente salvo que sea cancelada con al menos 24 horas de anticipación al período de renovación." },
      { titulo: "7. Limitación de responsabilidad", cuerpo: "Fynx es una herramienta de apoyo a la gestión financiera personal. Las recomendaciones generadas por la aplicación son orientativas y no constituyen asesoramiento financiero profesional. Fynx no se responsabiliza por decisiones financieras tomadas con base en la información proporcionada por la aplicación." },
      { titulo: "8. Modificaciones", cuerpo: "Nos reservamos el derecho de modificar estos términos en cualquier momento. Los cambios entrarán en vigor inmediatamente después de su publicación en la aplicación. El uso continuado de Fynx tras la publicación de cambios constituye su aceptación de los nuevos términos." },
      { titulo: "9. Contacto", cuerpo: "Para consultas relacionadas con estos términos, puede contactarnos a través de: soporte@fynxelite.app" }
    ],
    privacidad: [
      { titulo: "1. Información que recopilamos", cuerpo: "Fynx recopila la siguiente información: (a) Datos de cuenta: correo electrónico y contraseña cifrada para autenticación. (b) Datos financieros: transacciones, ingresos, gastos, metas y presupuestos que usted ingrese voluntariamente. (c) Datos de uso: métricas anónimas de rendimiento de la aplicación." },
      { titulo: "2. Cómo usamos su información", cuerpo: "Utilizamos su información exclusivamente para: proporcionar y mejorar el servicio de Fynx, sincronizar sus datos entre dispositivos, calcular su Score Fynx y generar reportes financieros personalizados. No vendemos ni compartimos su información personal con terceros con fines publicitarios." },
      { titulo: "3. Firebase y Google", cuerpo: "Fynx utiliza Firebase (Google LLC) para autenticación y almacenamiento en la nube. Google procesa los datos de acuerdo con su Política de Privacidad. Los datos se almacenan en servidores ubicados en Estados Unidos con cifrado en tránsito y en reposo." },
      { titulo: "4. Almacenamiento local", cuerpo: "La mayoría de sus datos financieros se almacenan localmente en su dispositivo mediante AsyncStorage. Si desinstala la aplicación, estos datos se eliminarán permanentemente del dispositivo. Los datos sincronizados en la nube permanecen hasta que solicite su eliminación." },
      { titulo: "5. Seguridad", cuerpo: "Implementamos medidas técnicas y organizativas para proteger su información: cifrado de contraseñas, comunicaciones HTTPS, autenticación Firebase y, opcionalmente, acceso biométrico. Sin embargo, ningún sistema de seguridad es infalible." },
      { titulo: "6. Sus derechos", cuerpo: "Usted tiene derecho a: acceder a sus datos personales, corregir información inexacta, solicitar la eliminación de su cuenta y datos asociados, exportar su historial financiero (función Premium) y retirar su consentimiento para el procesamiento de datos en cualquier momento." },
      { titulo: "7. Menores de edad", cuerpo: "Fynx no está dirigida a menores de 16 años. No recopilamos conscientemente información de menores. Si detectamos que hemos recopilado datos de un menor, procederemos a eliminarlos de forma inmediata." },
      { titulo: "8. Cambios en la política", cuerpo: "Notificaremos cualquier cambio significativo en esta política a través de la aplicación con al menos 30 días de anticipación. El uso continuado del servicio implica la aceptación de la política actualizada." },
      { titulo: "9. Contacto", cuerpo: "Para ejercer sus derechos o realizar consultas sobre privacidad: privacidad@fynxelite.app\n\nÚltima actualización: mayo 2026" }
    ]
  },

  notificaciones: {
    titulo: "Notificaciones",
    subtitulo: "Tus recordatorios y alertas pendientes.",
    todoAlDia: "Todo al día",
    sinPagos: "No tienes pagos pendientes próximos.",
    venceEl: (d) => `Vence el día ${d}`,
    venceHoy: "Vence hoy",
    vencioHace: (d) => `Venció hace ${d} días`,
    venceEn: (d) => `Vence en ${d} días`,
  },

  // ── Perfil ────────────────────────────────────────────────────────────────
  perfil: {
    titulo:    "Perfil",
    deudas:    "Deudas",
    metas:     "Metas",
    recordatorios: "Recordatorios",
    sinDeudas: "Sin deudas registradas.",
    sinRecord: "Sin recordatorios.",
    nuevaDeuda:"Nueva deuda",
    nuevoRecord:"Nuevo recordatorio",
    categoryBudgets: "Presupuestos de Categoría",
    socialScore: "Social Score",
  },

  // ── Gráfica ───────────────────────────────────────────────────────────────
  grafica: {
    titulo:    "Gráfica de tendencias",
    ingresos:  "Ingresos",
    gastos:    "Gastos",
    balance:   "Balance",
    sinDatos:  "Sin datos suficientes para mostrar la gráfica.",
  },

  // ── Setup inicial ─────────────────────────────────────────────────────────
  setup: {
    titulo:      "Configuración inicial",
    paso1:       "Tu perfil financiero",
    paso2:       "Límites de presupuesto",
    paso3:       "Categorías de gasto",
    subtitulo1:  "Personaliza Fynx según tus necesidades.",
    subtitulo2:  "Define cuánto quieres gastar por categoría.",
    subtitulo3:  "Selecciona las que usarás con más frecuencia.",
    resumen:     "RESUMEN",
    comenzar:    "Comenzar",
    guardando:   "Guardando...",
  },

  widgets: {
    presupuestos: "PRESUPUESTOS",
    sinPresupuestos: "Sin presupuestos configurados",
    metasAhorro: "METAS DE AHORRO",
    sinMetas: "Sin metas configuradas",
    compromisoAhorro: "COMPROMISO DE AHORRO",
    fynxScore: "FYNX SCORE",
    tarsInsight: "INSIGHT DE TARS",
    flujoCaja: "FLUJO DE CAJA",
  },
};
